// Generates dist/sw.js from the built site.
//
// Runs after `astro build`. Reads every file in dist/, builds the offline
// precache manifest (all HTML pages + hashed _astro assets + shell files),
// and stamps the service worker with a version derived from the manifest
// itself. Any deploy that changes the site therefore changes sw.js
// byte-for-byte, so browsers pick up the new worker and its activate step
// prunes stale caches — no manual version bumping.
/* global console, process */
import { createHash } from "node:crypto";
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, sep } from "node:path";
import { fileURLToPath } from "node:url";

const distDir = join(dirname(fileURLToPath(import.meta.url)), "..", "dist");

if (!statSync(distDir, { throwIfNoEntry: false })?.isDirectory()) {
  console.error("generate-sw: dist/ not found — run `astro build` first.");
  process.exit(1);
}

// Fonts: force font-display: optional in the built CSS. With `swap`, a font
// that lands after first paint triggers a full text re-layout inside the TBT
// window (Lighthouse measures this as a bimodal ~90/96 on tool pages).
// `optional` renders with the system fallback when the font misses the short
// block window and never swaps afterwards, so a post-FCP re-layout can never
// happen. The fallback stacks in global.css (system-ui/-apple-system) sit
// close to Inter, so the only real-world cost is on very slow connections.
function forceFontDisplayOptional() {
  for (const file of walk(distDir)) {
    if (!file.endsWith(".css")) continue;
    const css = readFileSync(file, "utf8");
    if (!css.includes("font-display: swap")) continue;
    writeFileSync(file, css.replaceAll("font-display: swap", "font-display: optional"), "utf8");
  }
}
forceFontDisplayOptional();

// Root shell files worth keeping offline (favicons, manifest icons).
// og-image.png is a social-share image — excluded from the offline shell.
const ROOT_SHELL = [
  "favicon.svg",
  "favicon-96x96.png",
  "favicon.ico",
  "apple-touch-icon.png",
  "web-app-manifest-192x192.png",
  "web-app-manifest-512x512.png",
  "site.webmanifest",
];

function walk(dir) {
  const out = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const st = statSync(full);
    if (st.isDirectory()) out.push(...walk(full));
    else out.push(full);
  }
  return out;
}

function toUrl(relPath) {
  const normalized = relPath.split(sep).join("/");
  if (normalized === "index.html") return "/";
  if (normalized.endsWith("/index.html")) {
    return "/" + normalized.slice(0, normalized.length - "index.html".length);
  }
  return "/" + normalized;
}

const files = walk(distDir);
const precache = [];

for (const file of files) {
  const rel = file.slice(distDir.length + 1);
  const url = toUrl(rel);

  if (rel.endsWith(".html") && url !== "/sw.js") {
    precache.push(url);
  } else if (rel.startsWith("_astro" + sep)) {
    precache.push(url);
  } else if (ROOT_SHELL.includes(rel)) {
    precache.push(url);
  }
}

precache.sort();
const version = createHash("sha1").update(JSON.stringify(precache)).digest("hex").slice(0, 12);
const precacheJson = JSON.stringify(precache);
const offlineUrl = "/offline.html";

// NOTE: keep this worker dependency-free and free of backticks / ${ } so it
// can live inside the template below.
const swSource = `/* Generated by scripts/generate-sw.mjs — do not edit. */
var CACHE = "fjt-" + "${version}";
var PRECACHE = ${precacheJson};
var OFFLINE = "${offlineUrl}";

self.addEventListener("install", function (event) {
  event.waitUntil(
    caches.open(CACHE).then(function (cache) {
      // add() each entry separately so one 404 can never sink the whole
      // install — everything that exists gets cached.
      return Promise.allSettled(
        PRECACHE.map(function (url) { return cache.add(url); })
      );
    })
  );
  self.skipWaiting();
});

self.addEventListener("activate", function (event) {
  event.waitUntil(
    caches.keys().then(function (keys) {
      return Promise.all(
        keys
          .filter(function (key) { return key !== CACHE; })
          .map(function (key) { return caches.delete(key); })
      );
    })
  );
  self.clients.claim();
});

self.addEventListener("fetch", function (event) {
  var req = event.request;
  if (req.method !== "GET") return;

  var url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  // HTML navigations: network first, then cache, then the offline page.
  if (req.mode === "navigate") {
    event.respondWith(
      fetch(req)
        .then(function (res) {
          if (res.ok) {
            var clone = res.clone();
            caches.open(CACHE).then(function (cache) { cache.put(req, clone); });
          }
          return res;
        })
        .catch(function () {
          return caches.match(req).then(function (hit) {
            return hit || caches.match(OFFLINE);
          });
        })
    );
    return;
  }

  // Everything else (hashed css/js/woff2/workers, icons): cache first, then
  // fetch and populate. Hashed filenames are immutable, so cache-first is
  // correct and fast.
  event.respondWith(
    caches.match(req).then(function (hit) {
      if (hit) return hit;
      return fetch(req).then(function (res) {
        if (res.ok) {
          var clone = res.clone();
          caches.open(CACHE).then(function (cache) { cache.put(req, clone); });
        }
        return res;
      }).catch(function () {
        return new Response("", { status: 503, statusText: "Offline" });
      });
    })
  );
});
`;

writeFileSync(join(distDir, "sw.js"), swSource, "utf8");
console.log(
  `generate-sw: precached ${precache.length} files (${version}) -> dist/sw.js`,
);